"""rename merchant_clean to merchant

Revision ID: 3d12f4ed5370
Revises: ad4bf6697a81
Create Date: 2026-01-29 16:23:39.259979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d12f4ed5370'
down_revision: Union[str, Sequence[str], None] = 'ad4bf6697a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'transaction_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'merchant_clean', new_column_name='merchant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant', new_column_name='merchant_clean')
    op.alter_column('statements', 'transaction_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
